config/routes.rb
Rails.application.routes.draw do
  resource :map, only: [:show]
  get 'searches/admin'
# 顧客用
# URL /user/sign_in ...
devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  root to: 'homes#top'
   get 'admin' => 'homes#index'

   get "search" => "searches#search"

  end

scope module: :user do
  root to: 'homes#top'

  get "search" => "searches#search"

  #マイページ
  get "customers/mypage" => "customers#show"


  #投稿用
  get 'posts/new'
  post 'posts' => 'posts#create'

  #一覧用
  get 'posts/index'

  #詳細用
  get 'posts.:id' => 'posts#show'

  #編集用
  get 'posts.:id/edit' => 'posts#edit'
  patch 'posts.:id' => 'posts#update'

  #タグの検索で使用する
  get "search_tag" => "posts#search_tag"

  resources :post_comments, only: [:create]

end





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  

  # タグのリレーションのみ記載
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  
  validates :address, presence: true
  
  geocoded_by :address
  after_validation :geocode


  def save_tags(tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # 新しいタグを保存
    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(name:new_name)
      self.tags << tag
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_comments, dependent: :destroy
  has_many :posts, dependent: :destroy

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/customers_controller.rb
class User::CustomersController < ApplicationController
  
  def show
    @customer = current_user
    @posts = @customer.posts
    @post_tag = @posts.name
  end
  
 

  private

  def customer_params
    params.require(:customers).permit(:name, :introduction)
  end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @posts = Post.order(created_at: :desc).limit(4)
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post = post.id
    comment.save
    redirect_to root_path
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
     # 受け取った値を,で区切って配列にする
    tag_list = params[:post][:tag].split(',')
    if @post.save
      @post.save_tags(tag_list)
      redirect_to posts_index_path, notice:'投稿が完了しました'
    else
      render :new
    end
  end

  def index
    @posts = Post.all
    @tag_list = Tag.all
    respond_to do |format|
      format.html do
        @posts = Post.all
      end
      format.json do
        @posts = Post.all
      end
    end
  end

  def show
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:tag).join(',')
    @post_tags = @post.tags
    @post_comment = Post.new
  end

  def search_tag
    #検索結果画面でもタグ一覧表示
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts
  end


private
  def post_params
    params.require(:post).permit(:image, :introduction, :star, :address)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
 def after_sign_in_path_for(resource)
    root_path
 end
  
 def after_sign_out_path_for(resource)
    root_path
 end
  
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user/customers_helper.rb
module User::CustomersHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/searches_helper.rb
module User::SearchesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/posts/edit.html.erb
<%= form_with model: post , local: true do |f| %>
：
	# ここを追加
        <label>タグ(,で区切ると複数タグ登録できます)</label>
        <%= f.text_field :name,value: @tag_list, class: 'form-control' %>
：
      <% if post.new_record? %>
        <%= f.submit '新規作成', class: "btn btn-success mt-4" %>
      <% else %>
        <%= f.submit '更新する', class: "btn btn-success mt-4" %>
      <% end %>
：
<% end %>

app/views/user/posts/index.html.erb
<h1>投稿一覧</h1>

<!--タグリスト-->
  <% @tag_list.each do |list|%>
    <i class="fa-sharp fa-solid fa-tag"></i>
    <%=link_to list.name,search_tag_path(tag_id: list.id) %>
    <%="(#{list.posts.count})" %>
  <% end %>

  <div class="message">
  <%= flash[:notice] %>
</div>

<table>

<tbody>

<% @posts.each do |post| %>
  <tr>
    <td><span>
    <%= link_to posts_path(post.id) do %>
    <%= image_tag post.image, width: 110, height: 80, 
        class: "img-resize, rounded mx-auto d-block", 
        style: "object-fit: cover;" %>
    <% end %>
    </span></td>
    <td><span><%= post.introduction %></span></td>

    <td><span>
    <div id="star_<%= post.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= post.id %>');
  if (elem == null) return;

  elem.innerHTML = "";
  let opt = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= post.star %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>
</span></td>
 <% end %>


</tr>
</tbody>

</table>

app/views/user/posts/new.html.erb
<h1>投稿</h1>
<%= form_with model: Post.new do |f| %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <h4>説明</h4>
  <%= f.text_area :introduction %>

  <h4>タグ</h4>
  <%= f.text_field :tag %>
  
  <!--★レビュー-->
  <div class="form-group" id="star">
  <%= f.label :star %>
  <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
  <div id="post_raty"></div>
  </div>
  
  <script>
   $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;
        
        elem.innerHTML = ""
        let opt = {  
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'post[star]',
        };
        raty(elem, opt);
   });
   </script>
  <!--★レビュー-->
  
  <div class="input-group mb-3 mt-5">
      <div class="input-group-prepend">
        <span class="input-group-text" aria-hidden="true"><i class="fa-solid fa-tenge-sign"></i></span>
      </div>
      <%= text_field_tag :zipcode, nil, class: "form-control", placeholder: "郵便番号" %>
    </div>
    <div class="input-group mb-3 mt-4">
      <div class="input-group-prepend">
        <span class="input-group-text" aria-hidden="true"><i class="fa-solid fa-location-dot"></i></span>
      </div>
      <%= f.text_field :address, class: "form-control", placeholder: "住所" %>
    </div>
  
  <%= f.submit '投稿' %>
<% end %>

<%= javascript_pack_tag "jpostal",  'data-turbolinks-track': 'reload' %>

app/views/user/posts/search_tag.html.erb
<h2>タグが<%=@tag.name%>の投稿一覧</h2>

  <!--タグリスト-->
  <% @tag_list.each do |list|%>
    <i class="fa-sharp fa-solid fa-tag"></i>
    <%=link_to list.name,search_tag_path(tag_id: list.id) %>
    <%="(#{list.posts.count})" %>
  <% end %>
  
<table>

<tbody>
  
 <% @posts.each do |post| %>
  <tr>
    <td><span>
    <%= link_to posts_path(post.id) do %>
    <%= image_tag post.image, width: 110, height: 80, 
        class: "img-resize, rounded mx-auto d-block", 
        style: "object-fit: cover;" %>
    <% end %>
    </span></td>
    <td><span><%= post.introduction %></span></td>
 <% end %>
 
 </table>

</tbody>

app/views/user/posts/show.html.erb
<!-- タグリスト -->
  

  <p><%= image_tag @post.image, width: 110, height: 80, 
        class: "img-resize, rounded mx-auto d-block", 
        style: "object-fit: cover;" %></p>
<p class="card-title">
  <span><i class="fa-solid fa-location-dot"></i> <%= @post.address %></span>
</p>

  <p><%= @post.introduction %></p>
  
  <div id="star_<%= @post.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= @post.id %>');
  if (elem == null) return;
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= @post.star %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>
  
  <div class="container">
  <div id="map"></div>
  </div>
  
  <% @post_tags.each do |tag| %>
  <i class="fa-sharp fa-solid fa-tag"><%= link_to tag.name,search_tag_path(tag_id: tag.id) %></i>
  <% end %>
  
  
  
  
  
  <%= javascript_pack_tag 'map', 'data-turbolinks-track': 'reload' %>