config/routes.rb
Rails.application.routes.draw do
  resource :map, only: [:show]
  get 'searches/admin'
# 顧客用
# URL /user/sign_in ...
devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  root to: 'homes#top'
   get 'admin' => 'homes#index'

   get "search" => "searches#search"

  end

scope module: :user do
  root to: 'homes#top'

  get "search" => "searches#search"

  #マイページ
  get "customers/mypage" => "customers#show"


  #投稿用
  get 'posts/new'
  post 'posts' => 'posts#create'

  #一覧用
  get 'posts/index'

  #詳細用
  get 'posts.:id' => 'posts#show'

  #編集用
  get 'posts.:id/edit' => 'posts#edit'
  patch 'posts.:id' => 'posts#update'

  #タグの検索で使用する
  get "search_tag" => "posts#search_tag"

  resources :post_comments, only: [:create]

end





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  

  # タグのリレーションのみ記載
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  
  validates :address, presence: true
  
  geocoded_by :address
  after_validation :geocode


  def save_tags(tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # 新しいタグを保存
    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(name:new_name)
      self.tags << tag
    end
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
   belongs_to :user
   belongs_to :customer
  
  
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags

  validates :name, presence:true, length:{maximum:50}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_comments, dependent: :destroy
  has_many :posts, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :search

  def search
    @q = Post.ransack(params[:q])
    @item = @q.result(distinct: true)
    @result = params[:q]&.values&.reject(&:blank?)
  end
  
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/searches_helper.rb
module User::SearchesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>推し活MAP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/8a0cd277b8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">

    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>推し活MAP</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>
                <li class="nav-item text-light my-3 mr-5">
                  <%= "#{current_user.name}さん" %>
                </li>
                <li>
                  <%= link_to 'マイページ', customers_mypage_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to '投稿一覧', posts_index_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to '投稿', posts_new_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
                </li>
              <% elsif admin_signed_in? %>
                <li>
                  <%= link_to "会員一覧", admin_root_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "投稿一覧", posts_index_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "レビュー一覧", root_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
                </li>
              <% else %>
                <li>
                  <%= link_to "ホーム", root_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "商品一覧", posts_index_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-light' %>
                </li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <% if controller_name != 'sessions' %>
<div class="search_form pe-3">
  <%= search_form_for @q, url: search_path, class:"row justify-content-end" do |f| %>
  <div class="col-md-4 p-0">

  </div>
  <div class="col-md-1 p-0">
    <button class="btn btn-outline-success" type="submit">
      <i class="fa-solid fa-magnifying-glass"></i>
    </button>
  </div>
  <% end %>
</div>
<% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
  </body>
</html>